export enum TopicCategory {
  TRENDING = 'DISCOVER.TRENDING_TAB',
  AI_FINANCE = 'DISCOVER.AI_FINANCE_TAB',
  FINANCIAL_INSIGHTS = 'DISCOVER.FINANCIAL_INSIGHTS_TAB',
  OTHER = 'DISCOVER.OTHER_TAB',
  MY_FAVORITES = 'DISCOVER.FAVORITES_TAB',
}
